// SPDX-License-Identifier: MIT
// Copyright (c) 2026 viaGraph B.V. (Whisper Security)

package projcfg

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
)

// pyenv.go writes the ONE wholly-Whisper-owned dotenv file that `whisper init python` emits:
// `.whisper/proxy.env`, carrying the loopback proxy variables so any Python agent framework
// (httpx/requests/urllib-based) egresses from the project's /128. The whole point is that this
// file lives entirely inside OUR `.whisper/` namespace — we NEVER read, open, or write a
// user-owned `./.env` or `./.envrc`, so a user's secrets file can never be clobbered.
//
// The file holds ONLY 127.0.0.1 loopback URLs — never a secret (the API key stays in the
// mode-0600 global config), so an accidental commit leaks nothing material. We still write it
// 0600 and self-ignore `.whisper/` for consistency with the rest of the project state.

// PyEnvResult reports what WriteProxyEnv did so the caller can print an honest summary.
type PyEnvResult struct {
	Created bool // the proxy.env did not exist and we created it (vs. updated/rewrote an existing one)
}

// WriteProxyEnv writes `.whisper/proxy.env` (atomic temp+rename, mode 0600) with the canonical
// proxy block for the given local proxy port, and ensures a self-ignoring `.whisper/.gitignore`
// (`*`) so the file stays out of VCS even if the repo's root `.gitignore` is locked or managed.
//
// Content is a pure function of port, so a re-run produces byte-identical output (idempotent).
// Because the whole file is Whisper-owned there is nothing of the user's to preserve — no merge
// logic is needed (simpler and safer than a surgical merge). The atomic temp file is created
// INSIDE `.whisper/` and renamed over the target, so an interrupted write can never leave a
// half/empty file, and the rename replaces the name rather than following a symlink at the
// target (clobber-safe).
func WriteProxyEnv(p Paths, port int) (PyEnvResult, error) {
	var res PyEnvResult

	if err := os.MkdirAll(p.WhisperDir, 0o700); err != nil {
		return res, fmt.Errorf("could not create %s: %w", p.WhisperDir, err)
	}

	// Refuse to write THROUGH a symlinked target (a symlinked .whisper/proxy.env -> ../.env would
	// otherwise let an atomic rename land outside our namespace on some platforms). Our writes
	// only ever target real files under .whisper/.
	if err := refuseSymlink(p.ProxyEnvFile); err != nil {
		return res, err
	}

	if _, err := os.Lstat(p.ProxyEnvFile); os.IsNotExist(err) {
		res.Created = true
	}

	if err := writeFileAtomic(p.ProxyEnvFile, proxyEnvContent(port), 0o600); err != nil {
		return res, err
	}

	// Belt-and-suspenders: self-ignore the whole .whisper/ dir from inside our own namespace, so
	// proxy.env/config/connect.pid stay out of git even when the root .gitignore can't be touched.
	// Best-effort — a failure here is never fatal (gitignore hygiene is a courtesy).
	selfIgnore := filepath.Join(p.WhisperDir, ".gitignore")
	if fi, err := os.Lstat(selfIgnore); os.IsNotExist(err) {
		_ = os.WriteFile(selfIgnore, []byte("# whisper — keep machine-local agent state out of VCS\n*\n"), 0o600)
	} else if err == nil && fi.Mode()&os.ModeSymlink != 0 {
		// A symlinked .whisper/.gitignore could redirect the write outside the namespace — skip it
		// (best-effort hygiene file; never fatal).
		_ = fi
	}

	return res, nil
}

// ProxyEnvContent returns the canonical Whisper proxy env block for a local proxy port —
// EXACTLY the bytes `whisper init <tool>` writes to .whisper/proxy.env — so other surfaces
// (the MCP whisper_egress_config tool) hand out the identical, already-proven strings
// instead of re-deriving their own (one mechanism, Ken-Thompson lean).
func ProxyEnvContent(port int) []byte { return proxyEnvContent(port) }

// proxyEnvContent renders the canonical dotenv proxy block for the given loopback port. It
// mirrors the canonical forms used by run.go's proxyInjectedEnv and settings.go: HTTP-CONNECT
// is PRIMARY (deps-free; honored by requests/httpx/urllib/openai/anthropic), SOCKS is additive
// (needs requests[socks]/httpx[socks]), and BOTH upper- and lower-case twins are emitted (Go,
// curl, and some libraries read the lowercase forms). NO_PROXY includes the IPv6 loopback `::1`.
func proxyEnvContent(port int) []byte {
	httpForm := fmt.Sprintf("http://127.0.0.1:%d", port)
	socks := fmt.Sprintf("socks5h://127.0.0.1:%d", port)
	const noProxy = "localhost,127.0.0.1,::1"

	var b bytes.Buffer
	b.WriteString("# whisper-managed — regenerated by `whisper init python`; do not edit; safe to delete.\n")
	b.WriteString("# Only loopback URLs live here — no secret. The HTTP-CONNECT proxy is deps-free;\n")
	b.WriteString("# SOCKS (ALL_PROXY) is additive and needs requests[socks]/httpx[socks].\n")
	// Uppercase (the conventional spelling most libraries read first).
	fmt.Fprintf(&b, "HTTP_PROXY=%s\n", httpForm)
	fmt.Fprintf(&b, "HTTPS_PROXY=%s\n", httpForm)
	fmt.Fprintf(&b, "ALL_PROXY=%s\n", socks)
	fmt.Fprintf(&b, "NO_PROXY=%s\n", noProxy)
	// Lowercase twins (Go's net/http, curl, libcurl-based tools).
	fmt.Fprintf(&b, "http_proxy=%s\n", httpForm)
	fmt.Fprintf(&b, "https_proxy=%s\n", httpForm)
	fmt.Fprintf(&b, "all_proxy=%s\n", socks)
	fmt.Fprintf(&b, "no_proxy=%s\n", noProxy)
	// Node >=22.21/>=24 honors HTTP(S)_PROXY for global fetch/undici only when this is set;
	// harmless (ignored) for Python and other runtimes — so the one file works for Node tools too.
	b.WriteString("NODE_USE_ENV_PROXY=1\n")
	return b.Bytes()
}

// writeFileAtomic writes data to path via a temp file in the SAME directory followed by an
// os.Rename, so a crash mid-write can never leave a truncated/empty file and the rename replaces
// the target name atomically (on the same volume). The temp file carries the final perms.
func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, "."+filepath.Base(path)+".tmp*")
	if err != nil {
		return fmt.Errorf("could not stage %s: %w", path, err)
	}
	tmpName := tmp.Name()
	// Best-effort cleanup if we bail before the rename.
	defer func() { _ = os.Remove(tmpName) }()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("could not write %s: %w", path, err)
	}
	if err := tmp.Chmod(perm); err != nil {
		// Chmod may be a no-op/unsupported on some platforms (Windows) — not fatal.
		_ = err
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("could not finalize %s: %w", path, err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("could not install %s: %w", path, err)
	}
	return nil
}

// refuseSymlink returns a clear error if path exists and is a symlink — so an attacker-planted
// `.whisper/proxy.env -> ../.env` can never turn our "namespaced" write into a clobber of a
// user file. A non-existent path (or a regular file) is fine.
func refuseSymlink(path string) error {
	fi, err := os.Lstat(path)
	if err != nil {
		return nil // missing ⇒ nothing to follow
	}
	if fi.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("%s is a symlink — refusing to write through it (remove it and re-run)", path)
	}
	return nil
}
