// SPDX-License-Identifier: MIT
// Copyright (c) 2026 viaGraph B.V. (Whisper Security)

package resolverprofile

import (
	"strings"
	"testing"
)

// The model-cluster tests for the LINUX side of the Tier-2 plan plus the
// OS-agnostic model itself: golden renders (the drop-in bytes, the forwarder
// unit, the dnscrypt stamp), the keyed/keyless forwarder fallback, the
// resolv.conf backup guards, and the pre-state guard semantics of the rendered
// scripts. Pure - they run on every build host.

const (
	t2LinDoH = "https://doh.whisper.online/tok_lin/dns-query"
	t2LinIP  = "2a04:2a01:0:53::42"
)

var (
	t2HostResolvedCF = Host{ResolvedActive: true, ForwarderKind: "cloudflared", ForwarderPath: "/usr/local/bin/cloudflared"}
	t2HostResolvedDC = Host{ResolvedActive: true, ForwarderKind: "dnscrypt-proxy", ForwarderPath: "/usr/bin/dnscrypt-proxy"}
	t2HostNoFwd      = Host{ResolvedActive: true}
)

func TestT2LinuxDNS53DropInGolden(t *testing.T) {
	r := Profile{Mode: ModeDNS53, OS: "linux", ResolverIPs: []string{t2LinIP}}.Render(t2HostNoFwd)
	if r.Mode != ModeDNS53 || r.OS != "linux" || r.ResolverIP != t2LinIP {
		t.Fatalf("rendered identity wrong: %+v", r)
	}
	if len(r.Apply) != 2 || r.Apply[0].File == nil {
		t.Fatalf("dns53 on resolved = drop-in + restart, got %v", r.Apply)
	}
	// The drop-in is byte-exact: the server template's shape (DNS= + Domains=~.).
	want := "# Whisper resolver - generated by `whisper resolver`; revert with `whisper resolver --off`.\n" +
		"[Resolve]\nDNS=" + t2LinIP + "\nDomains=~.\n"
	if got := r.Apply[0].File.Content; got != want {
		t.Fatalf("drop-in golden mismatch:\n--- got\n%s\n--- want\n%s", got, want)
	}
	if r.Apply[0].File.Path != LinuxDropIn {
		t.Fatalf("drop-in path = %q, want %q", r.Apply[0].File.Path, LinuxDropIn)
	}
	if got := r.Apply[1].String(); got != "systemctl restart systemd-resolved" {
		t.Fatalf("restart step = %q", got)
	}
	// The plaintext tradeoff is stated, never hidden (conservative out).
	if !strings.Contains(strings.Join(r.Notes, "\n"), "unencrypted") {
		t.Fatalf("dns53 notes must state the plaintext tradeoff: %v", r.Notes)
	}
}

func TestT2LinuxDNS53ResolvConfFallback(t *testing.T) {
	r := Profile{Mode: ModeDNS53, OS: "linux", ResolverIPs: []string{t2LinIP}}.Render(Host{ResolvedActive: false})
	if len(r.Apply) != 2 {
		t.Fatalf("dns53 without resolved = backup + write, got %v", r.Apply)
	}
	// Backup only when resolv.conf exists AND no backup exists yet (the server
	// script's discipline - never clobber the original backup).
	cp := r.Apply[0]
	if cp.IfPresent != LinuxResolvConf || cp.IfAbsent != LinuxResolvBackup {
		t.Fatalf("backup guards wrong: %+v", cp)
	}
	if cp.String() != "[if "+LinuxResolvConf+" exists] [if "+LinuxResolvBackup+" absent] cp "+LinuxResolvConf+" "+LinuxResolvBackup {
		t.Fatalf("backup step = %q", cp.String())
	}
	if r.Apply[1].File == nil || r.Apply[1].File.Path != LinuxResolvConf ||
		r.Apply[1].File.Content != "nameserver "+t2LinIP+"\n" {
		t.Fatalf("resolv.conf write wrong: %+v", r.Apply[1])
	}
}

func TestT2LinuxDoHCloudflaredGolden(t *testing.T) {
	r := Profile{Mode: ModeDoH, OS: "linux", DohTemplate: t2LinDoH}.Render(t2HostResolvedCF)
	// unit -> daemon-reload -> enable -> restart -> WAIT -> drop-in -> restart resolved
	if len(r.Apply) != 7 {
		t.Fatalf("cloudflared DoH plan should have 7 steps, got %d: %v", len(r.Apply), r.Apply)
	}
	unit := r.Apply[0]
	if unit.File == nil || unit.File.Path != LinuxForwarderUnit {
		t.Fatalf("first step must write the forwarder unit: %+v", unit)
	}
	for _, want := range []string{
		"ExecStart=/usr/local/bin/cloudflared proxy-dns --address 127.0.0.1 --port 53 --upstream " + t2LinDoH,
		"Restart=always",
		"WantedBy=multi-user.target",
	} {
		if !strings.Contains(unit.File.Content, want) {
			t.Fatalf("unit is missing %q:\n%s", want, unit.File.Content)
		}
	}
	// The bounded wait sits BETWEEN the forwarder start and the resolver
	// repoint - never leave DNS half-configured.
	if r.Apply[4].WaitFor != "127.0.0.1:53" {
		t.Fatalf("step 5 must wait for the forwarder, got %+v", r.Apply[4])
	}
	if r.Apply[5].File == nil || r.Apply[5].File.Path != LinuxDropIn ||
		!strings.Contains(r.Apply[5].File.Content, "DNS=127.0.0.1") {
		t.Fatalf("the drop-in must point resolved at the local forwarder: %+v", r.Apply[5])
	}
}

func TestT2LinuxDoHDnscryptStampGolden(t *testing.T) {
	r := Profile{Mode: ModeDoH, OS: "linux", DohTemplate: "https://doh.whisper.online/whisper_live_DEVICE_abc123/dns-query"}.Render(t2HostResolvedDC)
	toml := r.Apply[0]
	if toml.File == nil || toml.File.Path != LinuxDNSCryptConfig {
		t.Fatalf("dnscrypt DoH must write the TOML first: %+v", toml)
	}
	// Golden stamp, computed independently (protocol 0x02, zero props, empty
	// addr, empty hashes, LP(host), LP(path)) - byte-identical to the server's
	// the server's own DoH stamp.
	wantStamp := "sdns://AgAAAAAAAAAAAAASZG9oLndoaXNwZXIub25saW5lJS93aGlzcGVyX2xpdmVfREVWSUNFX2FiYzEyMy9kbnMtcXVlcnk"
	if !strings.Contains(toml.File.Content, "stamp = '"+wantStamp+"'") {
		t.Fatalf("dnscrypt TOML stamp golden mismatch:\n%s", toml.File.Content)
	}
	// The explicit bootstrap keeps the stamp's hostname resolvable without the
	// resolver being installed (no loop) - the server template's guard.
	if !strings.Contains(toml.File.Content, "bootstrap_resolvers = ['9.9.9.9:53', '1.1.1.1:53']") {
		t.Fatalf("dnscrypt TOML must carry the IP bootstrap:\n%s", toml.File.Content)
	}
}

func TestT2DoHStampBareGolden(t *testing.T) {
	if got, want := DoHStamp(BareDoHURL), "sdns://AgAAAAAAAAAAAAASZG9oLndoaXNwZXIub25saW5lCi9kbnMtcXVlcnk"; got != want {
		t.Fatalf("bare stamp = %q, want %q", got, want)
	}
}

func TestT2DnscryptConfigVersionAdapts(t *testing.T) {
	// 2.1.0 renamed fallback_resolvers -> bootstrap_resolvers and BOTH lineages
	// FATAL on the other's key (proven live: stock Ubuntu 24.04's apt 2.0.45
	// exits "Unsupported key in configuration file: [bootstrap_resolvers]").
	cases := []struct{ version, wantKey string }{
		{"2.0.45", "fallback_resolvers"},
		{"2.0.45+ds1", "fallback_resolvers"},
		{"2.1.7", "bootstrap_resolvers"},
		{"2.1.14", "bootstrap_resolvers"},
		{"", "bootstrap_resolvers"},        // unknown -> modern
		{"garbage", "bootstrap_resolvers"}, // unparseable -> modern
	}
	for _, c := range cases {
		cfg := dnscryptConfig(t2LinDoH, c.version)
		if !strings.Contains(cfg, c.wantKey+" = ['9.9.9.9:53', '1.1.1.1:53']") {
			t.Fatalf("version %q must emit %s:\n%s", c.version, c.wantKey, cfg)
		}
		other := "bootstrap_resolvers"
		if c.wantKey == other {
			other = "fallback_resolvers"
		}
		if strings.Contains(cfg, other) {
			t.Fatalf("version %q must NOT emit %s (it fatals):\n%s", c.version, other, cfg)
		}
	}
}

func TestT2ForwarderVersionPolicy(t *testing.T) {
	// cloudflared removed proxy-dns in 2026.2.0 (proven live on 2026.8.2).
	for raw, removed := range map[string]bool{
		"cloudflared version 2026.8.2 (built 2026-08-14-12:17 UTC)": true,
		"cloudflared version 2026.2.0":                              true,
		"cloudflared version 2026.1.5 (built 2026-01-20)":           false, // 2026.1 still ships it
		"cloudflared version 2025.11.1":                             false,
		"":                                                          true, // unknown -> conservative: never install a crash-looping unit
		"garbage":                                                   true,
	} {
		if got := cloudflaredProxyDNSRemoved(raw); got != removed {
			t.Fatalf("cloudflaredProxyDNSRemoved(%q) = %v, want %v", raw, got, removed)
		}
	}
	// parseVersion is liberal in what it accepts.
	if v := parseVersion("dnscrypt-proxy 2.0.45"); len(v) != 3 || v[0] != 2 || v[1] != 0 || v[2] != 45 {
		t.Fatalf("parseVersion embedded = %v", v)
	}
	if v := parseVersion("built 2026 then 2.1.7 here"); len(v) != 3 || v[0] != 2 || v[1] != 1 || v[2] != 7 {
		t.Fatalf("parseVersion must skip lone numbers: %v", v)
	}
	if parseVersion("no digits at all") != nil {
		t.Fatalf("parseVersion must yield nil on no version")
	}
	if !versionAtLeast([]int{2, 1}, 2, 1) || versionAtLeast([]int{2, 0, 45}, 2, 1) || !versionAtLeast([]int{3}, 2, 1) {
		t.Fatalf("versionAtLeast comparisons wrong")
	}
}

func TestT2LinuxNoUsableForwarderCarriesRejectedNote(t *testing.T) {
	// A found-but-unusable forwarder (new cloudflared) is explained, so the
	// install guidance never reads as blind.
	h := Host{ResolvedActive: true, ForwarderRejected: "cloudflared is installed but no longer ships a DNS forwarder (proxy-dns was removed in cloudflared 2026.2.0) - it cannot serve this profile"}
	r := Profile{Mode: ModeDoH, OS: "linux", DohTemplate: BareDoHURL}.Render(h)
	if len(r.Apply) != 0 {
		t.Fatalf("no usable forwarder must yield no apply steps: %v", r.Apply)
	}
	notes := strings.Join(r.Notes, "\n")
	if !strings.Contains(notes, "proxy-dns was removed") || !strings.Contains(notes, "sudo apt install dnscrypt-proxy") {
		t.Fatalf("notes must explain the rejection AND the install line: %v", r.Notes)
	}
}

func TestT2LinuxDoHNoForwarderKeyedFallsBackToDNS53(t *testing.T) {
	// Keyed (a /128 is available): the render degrades to the dedicated :53
	// resolver with a clear note - never a dead end (Postel).
	r := Profile{Mode: ModeDoH, OS: "linux", DohTemplate: t2LinDoH, ResolverIPs: []string{t2LinIP}}.Render(t2HostNoFwd)
	if r.Mode != ModeDNS53 {
		t.Fatalf("no-forwarder keyed DoH must fall back to dns53, got %s", r.Mode)
	}
	if len(r.Apply) == 0 || r.Apply[0].File == nil || !strings.Contains(r.Apply[0].File.Content, "DNS="+t2LinIP) {
		t.Fatalf("fallback must point resolved at the /128: %v", r.Apply)
	}
	if !strings.Contains(r.Notes[0], "no usable DoH forwarder") {
		t.Fatalf("the fallback must lead with the why: %v", r.Notes)
	}
}

func TestT2LinuxDoHNoForwarderNoIPExplains(t *testing.T) {
	// No forwarder and no /128 to fall back to: no apply steps, and the notes
	// carry BOTH the install line and the keyed :53 path - a clear next step.
	r := Profile{Mode: ModeDoH, OS: "linux", DohTemplate: BareDoHURL}.Render(t2HostNoFwd)
	if len(r.Apply) != 0 {
		t.Fatalf("no-forwarder no-IP DoH must not produce apply steps: %v", r.Apply)
	}
	notes := strings.Join(r.Notes, "\n")
	if !strings.Contains(notes, "sudo apt install dnscrypt-proxy") || !strings.Contains(notes, "dedicated :53 resolver") {
		t.Fatalf("notes must carry the install line and the keyed :53 path: %v", r.Notes)
	}
	// Even a plan that cannot apply still carries the universal revert.
	if len(r.Revert) == 0 {
		t.Fatalf("the universal revert must always be present")
	}
}

func TestT2LinuxRevertIsUniversalAndGuarded(t *testing.T) {
	r := Profile{Mode: ModeDNS53, OS: "linux", ResolverIPs: []string{t2LinIP}}.Render(t2HostNoFwd)
	joined := ""
	for _, s := range r.Revert {
		joined += s.String() + "\n"
	}
	// One undo covers every apply shape: forwarder unit, dnscrypt config,
	// drop-in, resolv.conf backup - each behind its own presence guard.
	for _, want := range []string{
		"[if " + LinuxForwarderUnit + " exists] systemctl disable --now whisper-dns",
		"[if " + LinuxForwarderUnit + " exists] remove " + LinuxForwarderUnit,
		"[if " + LinuxDNSCryptConfig + " exists] remove " + LinuxDNSCryptConfig,
		"[if " + LinuxDropIn + " exists] remove " + LinuxDropIn,
		"[if " + LinuxDropIn + " exists] systemctl restart systemd-resolved",
		"[if " + LinuxResolvBackup + " exists] cp " + LinuxResolvBackup + " " + LinuxResolvConf,
		"[if " + LinuxResolvBackup + " exists] remove " + LinuxResolvBackup,
	} {
		if !strings.Contains(joined, want) {
			t.Fatalf("universal revert is missing %q:\n%s", want, joined)
		}
	}
}

func TestT2LinuxScriptCapturesPreStateGuards(t *testing.T) {
	// The rendered bash must evaluate guards BEFORE any step runs (the applier's
	// semantics): "restart resolved if the drop-in existed" still fires after an
	// earlier step removed the drop-in.
	r := Profile{Mode: ModeDoH, OS: "linux", DohTemplate: t2LinDoH}.Render(t2HostResolvedCF)
	script := r.RevertScript()
	if !strings.Contains(script, "# Pre-state guards (evaluated before any step runs).") {
		t.Fatalf("revert script must capture pre-state guards:\n%s", script)
	}
	// Guard capture lines precede the first guarded action.
	capIdx := strings.Index(script, "g0=0;")
	actIdx := strings.Index(script, "if [ \"$g0\" -eq 1 ]; then")
	if capIdx < 0 || actIdx < 0 || capIdx > actIdx {
		t.Fatalf("guard capture must precede its use:\n%s", script)
	}
	// set -e discipline plus the shebang: the block is directly runnable.
	if !strings.HasPrefix(script, "#!/usr/bin/env bash\n") || !strings.Contains(script, "set -euo pipefail") {
		t.Fatalf("script must be a strict, runnable bash block:\n%s", script)
	}
}

func TestT2LinuxApplyScriptHeredocsAndWait(t *testing.T) {
	r := Profile{Mode: ModeDoH, OS: "linux", DohTemplate: t2LinDoH}.Render(t2HostResolvedCF)
	script := r.ApplyScript()
	for _, want := range []string{
		"cat > " + LinuxForwarderUnit + " <<'WHISPER_EOF'",
		"mkdir -p /etc/systemd/system",
		"systemctl enable --now whisper-dns",
		"/dev/tcp/127.0.0.1/53", // the bounded wait probe
		"cat > " + LinuxDropIn + " <<'WHISPER_EOF'",
	} {
		if !strings.Contains(script, want) {
			t.Fatalf("apply script is missing %q:\n%s", want, script)
		}
	}
}

func TestT2LinuxMatchDomainsNarrows(t *testing.T) {
	r := Profile{Mode: ModeDNS53, OS: "linux", ResolverIPs: []string{t2LinIP},
		MatchDomains: []string{"corp.example", "internal.example"}}.Render(t2HostNoFwd)
	if !strings.Contains(r.Apply[0].File.Content, "Domains=~corp.example ~internal.example") {
		t.Fatalf("match domains must narrow the Domains= line:\n%s", r.Apply[0].File.Content)
	}
}

func TestT2LinuxDNS53KeylessDegradesWithNote(t *testing.T) {
	r := Profile{Mode: ModeDNS53, OS: "linux"}.Render(t2HostNoFwd)
	if len(r.Apply) != 0 {
		t.Fatalf("keyless dns53 must not produce apply steps: %v", r.Apply)
	}
	if !strings.Contains(strings.Join(r.Notes, "\n"), "Whisper key") {
		t.Fatalf("keyless dns53 must explain the key path: %v", r.Notes)
	}
}

func TestT2StepStringForms(t *testing.T) {
	cases := []struct {
		s    Step
		want string
	}{
		{Step{Cmd: []string{"systemctl", "daemon-reload"}}, "systemctl daemon-reload"},
		{Step{Remove: "/etc/x", IfPresent: "/etc/x"}, "[if /etc/x exists] remove /etc/x"},
		{Step{WaitFor: "127.0.0.1:53"}, "wait until 127.0.0.1:53 answers (bounded, 30s)"},
		{Step{Shell: "echo hi"}, "echo hi"},
		{Step{Cmd: []string{"echo", "two words"}}, "echo 'two words'"},
		{Step{}, "(no-op)"},
	}
	for _, c := range cases {
		if got := c.s.String(); got != c.want {
			t.Fatalf("Step.String() = %q, want %q", got, c.want)
		}
	}
}
